/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '001' at '16-12-15 下午1:43' with Gradle 2.10
 *
 * @author 001, @date 16-12-15 下午1:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
