import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by '001' at '16-12-15 下午1:43' with Gradle 2.10
 *
 * @author 001, @date 16-12-15 下午1:43
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }


    public static void main(String[] args) {

        System.out.printf("what you know is all wrong");
    }
}
